[phases.setup]
providers = ["nodejs_20", "npm-9_x", "openssl", "curl", "wget"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"